### ISSUE TITLE
privacyPolicyClickBlock 这个回调没写 哈哈

### ISSUE THREAD

**Issue by greezi** [lishangjing-spec/lsj-PrivateProtocolAlert#1]
`[attrString yy_setTextHighlightRange:range2 color:self.highlightColor backgroundColor:[UIColor clearColor] tapAction:^(UIView * _Nonnull containerView, NSAttributedString * _Nonnull text, NSRange range, CGRect rect) {
            SFSafariViewController * safariVC = [[SFSafariViewController alloc]initWithURL:self.privacyPolicyURL];
            [self presentViewController:safariVC animated:NO completion:nil];
        }];`
改成
`[attrString yy_setTextHighlightRange:range2 color:self.highlightColor backgroundColor:[UIColor clearColor] tapAction:^(UIView * _Nonnull containerView, NSAttributedString * _Nonnull text, NSRange range, CGRect rect) {
kStrongSelf(self);
            if(self.privacyPolicyClickBlock){
                self.privacyPolicyClickBlock();
            }else{
                SFSafariViewController * safariVC = [[SFSafariViewController alloc]initWithURL:self.privacyPolicyURL];
                [self presentViewController:safariVC animated:NO completion:nil];
            }
        }];
`

**Comment by lishangjing-spec** [comment]
哈哈哈, 好尴尬啊，v0.3.0 补上了
