### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by shichuanyang** [lishangjing-spec/lsj-PrivateProtocolAlert#2]
![image](https://user-images.githubusercontent.com/75350000/194880337-b85b9a5a-9821-45f3-9f6e-07b593f9f743.png)

崩溃了 啥原因 占比还很高

**Comment by lishangjing-spec** [comment]
你这边能复现吗，这种一般是野指针，LSJPrivateProtocolAlert指针地址被回收了，也就是在什么位置对其进行了释放或者ARC计数器 -1 的行为，但是对象还在 顺便截图看下你的使用的代码，以及上面的错误信息，涉及的设备版本号。代码是开源的，你看下能不能复现

**Comment by lishangjing-spec** [comment]
SDK 的版本是 0.3.0 吗，是用pod导入的吗，有修改过内部的源码吗

**Comment by lishangjing-spec** [comment]
我大致的猜测是使用LSJPrivateProtocolAlert时，对 Block 的赋值未处理weak，导致循环引用，之后在项目中的其他位置，对LSJPrivateProtocolAlert，进行了一个销毁，但是因为存在循环引用的问题，导致 LSJPrivateProtocolAlert 仅地址被回收了，但是视图及内存还在，这时候点击确定，就会出现野指针的一个问题。 可以截图看下你的使用代码，后续我将会把Block的形式改为 delegate， 避免block的循环引用问题

**Comment by shichuanyang** [comment]
![image](https://user-images.githubusercontent.com/75350000/194981520-f8f279c8-9829-448f-a2e0-d7bfc24d02d3.png)
我用的是0.2.0

**Comment by lishangjing-spec** [comment]
我看你这里对代码进行了一个调整，是否存在循环引用的问题

**Comment by shichuanyang** [comment]
//
//  PrivateProtocolAlert.h
//  JMBaseProject
//
//  Created by 温州天媒软件 on 2021/3/29.
//  Copyright © 2021 liuny. All rights reserved.
//

@import UIKit;

NS_ASSUME_NONNULL_BEGIN

@interface LSJPrivateProtocolAlert : UIViewController

// 自定义确定按钮的样式
@property (nonatomic,strong) UIButton *sureButton;/**< 确认按钮 */

@property (nonatomic,strong) NSString *appName;/**< 设置应用名称 */
@property (nonatomic,strong) UIColor *nomalTextColor;/**<  设置文字颜色 Default: 333333 */
@property (nonatomic,strong) UIColor *highlightColor;/**<  设置《用户协议》《隐私政策》颜色 Default: 4A90E2 */


// MARK: 隐私政策
// 设置 URL
@property (nonatomic,strong) NSURL *userAgreementURL;/**< 用户协议地址 */
@property (nonatomic,strong) NSURL *privacyPolicyURL;/**< 隐私政策地址 */
@property (nonatomic,copy) NSString *content;/**条款详情 */
@property (nonatomic,copy) NSString *highlightServiceAgreementContent;/**用户协议按钮titile*/
@property (nonatomic,copy) NSString *highlightPrivacyPolicycontent;/**隐私政策按钮title */
@property (nonatomic,copy) NSString *agreeBtnTitle;/**同意按钮title */
@property (nonatomic,copy) NSString *disagreeBtnTitle;/**不同意按钮title */

// 或者如果不跳转web可自定义事件
@property (copy, nonatomic) void(^userAgreementClickBlock)(void);
@property (copy, nonatomic) void(^privacyPolicyClickBlock)(void);

// 完成事件
@property (copy, nonatomic) void(^completionBlock)(BOOL isFirst);


-(void)show;/**< 显示弹窗 */

- (void)setLayoutContent;
@end

NS_ASSUME_NONNULL_END




///////////////////////////////////////




//
//  PrivateProtocolAlert.m
//  JMBaseProject
//
//  Created by 温州天媒软件 on 2021/3/29.
//  Copyright © 2021 liuny. All rights reserved.
//

#import "LSJPrivateProtocolAlert.h"
#import "Masonry.h"
#import "YYLabel.h"
#import "NSAttributedString+YYText.h"
#import <SafariServices/SafariServices.h>

#define kWeakSelf(type)  __weak typeof(type) weak##type = type;
#define kStrongSelf(type) __strong typeof(type) type = weak##type;
#define LSJPrivateProtocolAlertUserDefaultsKey @"lsj-PrivateProtocolStandard"

@interface LSJPrivateProtocolAlert()
@property (nonatomic,strong) UIImageView *imgBG;/**< 蒙板 */
@property (nonatomic,strong) UIView *maskView;/**< 蒙板 */
@property (nonatomic,strong) UIView *containerView;/**< 弹窗容器 */
@property (nonatomic,strong) UILabel *titleLabel;/**< 弹窗 Title */
@property (nonatomic,strong) YYLabel *descLabel;/**< 详细描述文本 */
@property (nonatomic,strong) UIButton *cancelButton;/**< 取消按钮 */

@end

@implementation LSJPrivateProtocolAlert

- (instancetype)init{
    self = [super init];
    if(self){
        self.nomalTextColor = [UIColor colorWithRed:51.0/255.0 green:51.0/255.0 blue:51.0/255.0 alpha:1];
        self.highlightColor = [UIColor colorWithRed:74.0/255.0 green:144.0/255.0 blue:226.0/255.0 alpha:1];
        self.userAgreementURL = [NSURL URLWithString:@"https://www.jianshu.com"];
        self.privacyPolicyURL = [NSURL URLWithString:@"https://www.juejin.com"];
        NSDictionary *infoDictionary = [[NSBundle mainBundle] infoDictionary];
        self.appName = [infoDictionary objectForKey:@"CFBundleDisplayName"];
        self.sureButton.layer.masksToBounds = true;
        self.sureButton.layer.cornerRadius = self.sureButton.frame.size.height/2.0;
        self.sureButton.backgroundColor = [UIColor colorWithRed:83.0/255.0 green:162/255.0 blue:255.0/255.0 alpha:1];
        self.content = @"%@深知个人信息对您的重要性，因此我们将竭尽全力保障用户的隐私信息安全。\n\n您可以阅读完整版《用户协议》《隐私政策》详细了解我们如何保护您的权益。\n\n我们将严格按照政策要求使用和保护您的个人信息，如您同意以上内容，请点击同意，开始使用我们的产品与服务！";
        self.highlightServiceAgreementContent = @"《用户协议》";
        self.highlightPrivacyPolicycontent = @"《隐私政策》";
        self.agreeBtnTitle = @"同意，继续使用";
        self.disagreeBtnTitle = @"不同意，退出";

    }
    return self;
}

- (void)viewDidLoad{
    [super viewDidLoad];
    
    [self setupLayout];
}


// MARK: - Layout


-(void)setupLayout{
    
    self.view.backgroundColor = [UIColor whiteColor];
    
    [self.view addSubview:self.imgBG];
    [self.imgBG mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self.view);
    }];

    // Mask View
    [self.view addSubview:self.maskView];
    [self.maskView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self.view);
    }];
    
    // Container View
    [self.view addSubview:self.containerView];
    [self.containerView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.center.equalTo(self.view);
        make.width.mas_equalTo(310);
    }];
    
    // Title Label
    [self.containerView addSubview:self.titleLabel];
    [self.titleLabel mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerX.equalTo(self.containerView);
        make.top.equalTo(self.containerView.mas_top).offset(24);
    }];
    
    // Desc Label
    [self.containerView addSubview:self.descLabel];
    [self.descLabel mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.titleLabel.mas_bottom).offset(10);
        make.left.equalTo(self.containerView.mas_left).offset(20);
        make.right.equalTo(self.containerView.mas_right).offset(-20);
    }];
    
    // Sure Button
    [self.containerView addSubview:self.sureButton];
    [self.sureButton mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.descLabel.mas_bottom).offset(30.0);
        make.centerX.equalTo(self.containerView);
    }];
    
    // Cancel Button
    [self.containerView addSubview:self.cancelButton];
    [self.cancelButton mas_makeConstraints:^(MASConstraintMaker *make) {
        make.size.equalTo(self.sureButton);
        make.top.equalTo(self.sureButton.mas_bottom).offset(5);
        make.centerX.equalTo(self.sureButton);
        make.bottom.equalTo(self.containerView.mas_bottom).offset(-10);
    }];
    
}

- (void)setAgreeBtnTitle:(NSString *)agreeBtnTitle {
    _agreeBtnTitle = agreeBtnTitle;
    [_sureButton setTitle:_agreeBtnTitle forState:UIControlStateNormal];
}

- (void)setDisagreeBtnTitle:(NSString *)disagreeBtnTitle {
    _disagreeBtnTitle = disagreeBtnTitle;
    [_cancelButton setTitle:_disagreeBtnTitle forState:UIControlStateNormal];
}

- (void)setLayoutContent {
    
    
    NSString *contentString = [NSString stringWithFormat:self.content,self.appName];
    
    NSMutableAttributedString *attrString = [[NSMutableAttributedString alloc] initWithString:contentString];
    [attrString addAttribute:NSForegroundColorAttributeName value:self.nomalTextColor range:[contentString rangeOfString:contentString]];
    [attrString addAttribute:NSStrokeColorAttributeName value:self.nomalTextColor range:[contentString rangeOfString:contentString]];
    [attrString addAttribute:NSStrokeWidthAttributeName value:@0 range:[contentString rangeOfString:contentString]];

    NSRange range1 = [contentString rangeOfString:self.highlightServiceAgreementContent];
    NSRange range2 = [contentString rangeOfString:self.highlightPrivacyPolicycontent];

    kWeakSelf(self);
    [attrString yy_setTextHighlightRange:range1 color:self.highlightColor backgroundColor:[UIColor clearColor] tapAction:^(UIView * _Nonnull containerView, NSAttributedString * _Nonnull text, NSRange range, CGRect rect) {
        kStrongSelf(self);
        if(self.userAgreementClickBlock){
            self.userAgreementClickBlock();
        }else{
            SFSafariViewController * safariVC = [[SFSafariViewController alloc]initWithURL:self.userAgreementURL];
            [self presentViewController:safariVC animated:NO completion:nil];
        }
    }];
    
    [attrString yy_setTextHighlightRange:range2 color:self.highlightColor backgroundColor:[UIColor clearColor] tapAction:^(UIView * _Nonnull containerView, NSAttributedString * _Nonnull text, NSRange range, CGRect rect) {
        SFSafariViewController * safariVC = [[SFSafariViewController alloc]initWithURL:self.privacyPolicyURL];
        [self presentViewController:safariVC animated:NO completion:nil];
    }];
    [attrString yy_setLineSpacing:5 range:NSMakeRange(0, contentString.length)];
    
    self.descLabel.attributedText = attrString;
    self.descLabel.font = [UIFont systemFontOfSize:13];

}

// MARK: - Method

-(void)show{
    NSString *guide = [[NSUserDefaults standardUserDefaults] objectForKey:LSJPrivateProtocolAlertUserDefaultsKey];
    if(guide){
        if(self.completionBlock){
            self.completionBlock(NO);
        }   
    }else{
        [UIApplication sharedApplication].delegate.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
        [[UIApplication sharedApplication].delegate.window makeKeyAndVisible];
        [UIApplication sharedApplication].delegate.window.backgroundColor = [UIColor whiteColor];
        [UIApplication sharedApplication].delegate.window.rootViewController = self;
    }
}


-(void)cancelButtonClick{
    abort();
}

-(void)sureButtonClick{
    [[NSUserDefaults standardUserDefaults] setObject:@"1" forKey:LSJPrivateProtocolAlertUserDefaultsKey];
    [[NSUserDefaults standardUserDefaults] synchronize];
    if(self.completionBlock){
        self.completionBlock(YES);
    }
}


// MARK: - Lazy
-(UIView *)maskView{
    if (!_maskView) {
        _maskView = [UIView new];
        _maskView.userInteractionEnabled = true;
        _maskView.backgroundColor = [UIColor blackColor];
        _maskView.alpha = 0.4;
    }
    return _maskView;
}

-(UIView *)containerView{
    if (!_containerView) {
        _containerView = [UIView new];
        _containerView.backgroundColor = [UIColor whiteColor];
        _containerView.layer.cornerRadius = 10;
        _containerView.layer.masksToBounds = true;
    }
    return _containerView;
}

-(UILabel *)titleLabel{
    if(!_titleLabel){
        _titleLabel = [UILabel new];
    }
    return _titleLabel;
}

-(YYLabel *)descLabel{
    if (!_descLabel) {
        _descLabel = [YYLabel new];
        _descLabel.preferredMaxLayoutWidth = 270;
        _descLabel.numberOfLines = 0;
    }
    return _descLabel;
}

-(UIButton *)sureButton{
    if(!_sureButton){
        CGSize size = CGSizeMake(270, 40);
        _sureButton = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, size.width, size.height)];
                
        [_sureButton mas_makeConstraints:^(MASConstraintMaker *make) {
            make.size.mas_equalTo(CGSizeMake(size.width, size.height));
        }];
        
        [_sureButton addTarget:self action:@selector(sureButtonClick) forControlEvents:UIControlEventTouchUpInside];
        
        [_sureButton setTitleColor:UIColor.whiteColor forState:UIControlStateNormal];
        _sureButton.titleLabel.font = [UIFont systemFontOfSize:14];
        [_sureButton setTitle:self.agreeBtnTitle forState:UIControlStateNormal];
    }
    return _sureButton;
}



-(UIButton *)cancelButton{
    if (!_cancelButton) {
        _cancelButton = [UIButton new];
        [_cancelButton addTarget:self action:@selector(cancelButtonClick) forControlEvents:UIControlEventTouchUpInside];
        [_cancelButton setTitle:self.disagreeBtnTitle forState:UIControlStateNormal];
        _cancelButton.titleLabel.font = [UIFont systemFontOfSize:13];
        [_cancelButton setTitleColor:[UIColor colorWithRed:51.0/255.0 green:51.0/255.0 blue:51.0/255.0 alpha:.7] forState:UIControlStateNormal];
    }
    return _cancelButton;
}

- (UIImageView *)imgBG {
    if (!_imgBG) {
        _imgBG = [[UIImageView alloc] init];
        _imgBG.contentMode = UIViewContentModeScaleAspectFill;
        _imgBG.image = [UIImage imageNamed:@"qidongye"];
    }
    return _imgBG;
}

@end

**Comment by shichuanyang** [comment]
```
@import UIKit;

NS_ASSUME_NONNULL_BEGIN

@interface LSJPrivateProtocolAlert : UIViewController

// 自定义确定按钮的样式
@property (nonatomic,strong) UIButton *sureButton;/**< 确认按钮 */

@property (nonatomic,strong) NSString *appName;/**< 设置应用名称 */
@property (nonatomic,strong) UIColor *nomalTextColor;/**<  设置文字颜色 Default: 333333 */
@property (nonatomic,strong) UIColor *highlightColor;/**<  设置《用户协议》《隐私政策》颜色 Default: 4A90E2 */


// MARK: 隐私政策
// 设置 URL
@property (nonatomic,strong) NSURL *userAgreementURL;/**< 用户协议地址 */
@property (nonatomic,strong) NSURL *privacyPolicyURL;/**< 隐私政策地址 */
@property (nonatomic,copy) NSString *content;/**条款详情 */
@property (nonatomic,copy) NSString *highlightServiceAgreementContent;/**用户协议按钮titile*/
@property (nonatomic,copy) NSString *highlightPrivacyPolicycontent;/**隐私政策按钮title */
@property (nonatomic,copy) NSString *agreeBtnTitle;/**同意按钮title */
@property (nonatomic,copy) NSString *disagreeBtnTitle;/**不同意按钮title */

// 或者如果不跳转web可自定义事件
@property (copy, nonatomic) void(^userAgreementClickBlock)(void);
@property (copy, nonatomic) void(^privacyPolicyClickBlock)(void);

// 完成事件
@property (copy, nonatomic) void(^completionBlock)(BOOL isFirst);


-(void)show;/**< 显示弹窗 */

- (void)setLayoutContent;
@end

NS_ASSUME_NONNULL_END

```

```
//  PrivateProtocolAlert.m
//  JMBaseProject
//
//  Created by 温州天媒软件 on 2021/3/29.
//  Copyright © 2021 liuny. All rights reserved.
//

#import "LSJPrivateProtocolAlert.h"
#import "Masonry.h"
#import "YYLabel.h"
#import "NSAttributedString+YYText.h"
#import <SafariServices/SafariServices.h>

#define kWeakSelf(type)  __weak typeof(type) weak##type = type;
#define kStrongSelf(type) __strong typeof(type) type = weak##type;
#define LSJPrivateProtocolAlertUserDefaultsKey @"lsj-PrivateProtocolStandard"

@interface LSJPrivateProtocolAlert()
@property (nonatomic,strong) UIImageView *imgBG;/**< 蒙板 */
@property (nonatomic,strong) UIView *maskView;/**< 蒙板 */
@property (nonatomic,strong) UIView *containerView;/**< 弹窗容器 */
@property (nonatomic,strong) UILabel *titleLabel;/**< 弹窗 Title */
@property (nonatomic,strong) YYLabel *descLabel;/**< 详细描述文本 */
@property (nonatomic,strong) UIButton *cancelButton;/**< 取消按钮 */

@end

@implementation LSJPrivateProtocolAlert

- (instancetype)init{
    self = [super init];
    if(self){
        self.nomalTextColor = [UIColor colorWithRed:51.0/255.0 green:51.0/255.0 blue:51.0/255.0 alpha:1];
        self.highlightColor = [UIColor colorWithRed:74.0/255.0 green:144.0/255.0 blue:226.0/255.0 alpha:1];
        self.userAgreementURL = [NSURL URLWithString:@"https://www.jianshu.com"];
        self.privacyPolicyURL = [NSURL URLWithString:@"https://www.juejin.com"];
        NSDictionary *infoDictionary = [[NSBundle mainBundle] infoDictionary];
        self.appName = [infoDictionary objectForKey:@"CFBundleDisplayName"];
        self.sureButton.layer.masksToBounds = true;
        self.sureButton.layer.cornerRadius = self.sureButton.frame.size.height/2.0;
        self.sureButton.backgroundColor = [UIColor colorWithRed:83.0/255.0 green:162/255.0 blue:255.0/255.0 alpha:1];
        self.content = @"%@深知个人信息对您的重要性，因此我们将竭尽全力保障用户的隐私信息安全。\n\n您可以阅读完整版《用户协议》《隐私政策》详细了解我们如何保护您的权益。\n\n我们将严格按照政策要求使用和保护您的个人信息，如您同意以上内容，请点击同意，开始使用我们的产品与服务！";
        self.highlightServiceAgreementContent = @"《用户协议》";
        self.highlightPrivacyPolicycontent = @"《隐私政策》";
        self.agreeBtnTitle = @"同意，继续使用";
        self.disagreeBtnTitle = @"不同意，退出";

    }
    return self;
}

- (void)viewDidLoad{
    [super viewDidLoad];
    
    [self setupLayout];
}


// MARK: - Layout


-(void)setupLayout{
    
    self.view.backgroundColor = [UIColor whiteColor];
    
    [self.view addSubview:self.imgBG];
    [self.imgBG mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self.view);
    }];

    // Mask View
    [self.view addSubview:self.maskView];
    [self.maskView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self.view);
    }];
    
    // Container View
    [self.view addSubview:self.containerView];
    [self.containerView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.center.equalTo(self.view);
        make.width.mas_equalTo(310);
    }];
    
    // Title Label
    [self.containerView addSubview:self.titleLabel];
    [self.titleLabel mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerX.equalTo(self.containerView);
        make.top.equalTo(self.containerView.mas_top).offset(24);
    }];
    
    // Desc Label
    [self.containerView addSubview:self.descLabel];
    [self.descLabel mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.titleLabel.mas_bottom).offset(10);
        make.left.equalTo(self.containerView.mas_left).offset(20);
        make.right.equalTo(self.containerView.mas_right).offset(-20);
    }];
    
    // Sure Button
    [self.containerView addSubview:self.sureButton];
    [self.sureButton mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.descLabel.mas_bottom).offset(30.0);
        make.centerX.equalTo(self.containerView);
    }];
    
    // Cancel Button
    [self.containerView addSubview:self.cancelButton];
    [self.cancelButton mas_makeConstraints:^(MASConstraintMaker *make) {
        make.size.equalTo(self.sureButton);
        make.top.equalTo(self.sureButton.mas_bottom).offset(5);
        make.centerX.equalTo(self.sureButton);
        make.bottom.equalTo(self.containerView.mas_bottom).offset(-10);
    }];
    
}

- (void)setAgreeBtnTitle:(NSString *)agreeBtnTitle {
    _agreeBtnTitle = agreeBtnTitle;
    [_sureButton setTitle:_agreeBtnTitle forState:UIControlStateNormal];
}

- (void)setDisagreeBtnTitle:(NSString *)disagreeBtnTitle {
    _disagreeBtnTitle = disagreeBtnTitle;
    [_cancelButton setTitle:_disagreeBtnTitle forState:UIControlStateNormal];
}

- (void)setLayoutContent {
    
    
    NSString *contentString = [NSString stringWithFormat:self.content,self.appName];
    
    NSMutableAttributedString *attrString = [[NSMutableAttributedString alloc] initWithString:contentString];
    [attrString addAttribute:NSForegroundColorAttributeName value:self.nomalTextColor range:[contentString rangeOfString:contentString]];
    [attrString addAttribute:NSStrokeColorAttributeName value:self.nomalTextColor range:[contentString rangeOfString:contentString]];
    [attrString addAttribute:NSStrokeWidthAttributeName value:@0 range:[contentString rangeOfString:contentString]];

    NSRange range1 = [contentString rangeOfString:self.highlightServiceAgreementContent];
    NSRange range2 = [contentString rangeOfString:self.highlightPrivacyPolicycontent];

    kWeakSelf(self);
    [attrString yy_setTextHighlightRange:range1 color:self.highlightColor backgroundColor:[UIColor clearColor] tapAction:^(UIView * _Nonnull containerView, NSAttributedString * _Nonnull text, NSRange range, CGRect rect) {
        kStrongSelf(self);
        if(self.userAgreementClickBlock){
            self.userAgreementClickBlock();
        }else{
            SFSafariViewController * safariVC = [[SFSafariViewController alloc]initWithURL:self.userAgreementURL];
            [self presentViewController:safariVC animated:NO completion:nil];
        }
    }];
    
    [attrString yy_setTextHighlightRange:range2 color:self.highlightColor backgroundColor:[UIColor clearColor] tapAction:^(UIView * _Nonnull containerView, NSAttributedString * _Nonnull text, NSRange range, CGRect rect) {
        SFSafariViewController * safariVC = [[SFSafariViewController alloc]initWithURL:self.privacyPolicyURL];
        [self presentViewController:safariVC animated:NO completion:nil];
    }];
    [attrString yy_setLineSpacing:5 range:NSMakeRange(0, contentString.length)];
    
    self.descLabel.attributedText = attrString;
    self.descLabel.font = [UIFont systemFontOfSize:13];

}

// MARK: - Method

-(void)show{
    NSString *guide = [[NSUserDefaults standardUserDefaults] objectForKey:LSJPrivateProtocolAlertUserDefaultsKey];
    if(guide){
        if(self.completionBlock){
            self.completionBlock(NO);
        }   
    }else{
        [UIApplication sharedApplication].delegate.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
        [[UIApplication sharedApplication].delegate.window makeKeyAndVisible];
        [UIApplication sharedApplication].delegate.window.backgroundColor = [UIColor whiteColor];
        [UIApplication sharedApplication].delegate.window.rootViewController = self;
    }
}


-(void)cancelButtonClick{
    abort();
}

-(void)sureButtonClick{
    [[NSUserDefaults standardUserDefaults] setObject:@"1" forKey:LSJPrivateProtocolAlertUserDefaultsKey];
    [[NSUserDefaults standardUserDefaults] synchronize];
    if(self.completionBlock){
        self.completionBlock(YES);
    }
}


// MARK: - Lazy
-(UIView *)maskView{
    if (!_maskView) {
        _maskView = [UIView new];
        _maskView.userInteractionEnabled = true;
        _maskView.backgroundColor = [UIColor blackColor];
        _maskView.alpha = 0.4;
    }
    return _maskView;
}

-(UIView *)containerView{
    if (!_containerView) {
        _containerView = [UIView new];
        _containerView.backgroundColor = [UIColor whiteColor];
        _containerView.layer.cornerRadius = 10;
        _containerView.layer.masksToBounds = true;
    }
    return _containerView;
}

-(UILabel *)titleLabel{
    if(!_titleLabel){
        _titleLabel = [UILabel new];
    }
    return _titleLabel;
}

-(YYLabel *)descLabel{
    if (!_descLabel) {
        _descLabel = [YYLabel new];
        _descLabel.preferredMaxLayoutWidth = 270;
        _descLabel.numberOfLines = 0;
    }
    return _descLabel;
}

-(UIButton *)sureButton{
    if(!_sureButton){
        CGSize size = CGSizeMake(270, 40);
        _sureButton = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, size.width, size.height)];
                
        [_sureButton mas_makeConstraints:^(MASConstraintMaker *make) {
            make.size.mas_equalTo(CGSizeMake(size.width, size.height));
        }];
        
        [_sureButton addTarget:self action:@selector(sureButtonClick) forControlEvents:UIControlEventTouchUpInside];
        
        [_sureButton setTitleColor:UIColor.whiteColor forState:UIControlStateNormal];
        _sureButton.titleLabel.font = [UIFont systemFontOfSize:14];
        [_sureButton setTitle:self.agreeBtnTitle forState:UIControlStateNormal];
    }
    return _sureButton;
}



-(UIButton *)cancelButton{
    if (!_cancelButton) {
        _cancelButton = [UIButton new];
        [_cancelButton addTarget:self action:@selector(cancelButtonClick) forControlEvents:UIControlEventTouchUpInside];
        [_cancelButton setTitle:self.disagreeBtnTitle forState:UIControlStateNormal];
        _cancelButton.titleLabel.font = [UIFont systemFontOfSize:13];
        [_cancelButton setTitleColor:[UIColor colorWithRed:51.0/255.0 green:51.0/255.0 blue:51.0/255.0 alpha:.7] forState:UIControlStateNormal];
    }
    return _cancelButton;
}

- (UIImageView *)imgBG {
    if (!_imgBG) {
        _imgBG = [[UIImageView alloc] init];
        _imgBG.contentMode = UIViewContentModeScaleAspectFill;
        _imgBG.image = [UIImage imageNamed:@"qidongye"];
    }
    return _imgBG;
}

@end

```

**Comment by shichuanyang** [comment]
这是我现在的文件内容

**Comment by lishangjing-spec** [comment]
能复现吗，看看最新的版本是否存在问题

**Comment by lishangjing-spec** [comment]
您好，现在还有这个问题，后来是如何处理的

**Comment by lishangjing-spec** [comment]
您好，该问题，是用户点击了不同意，我看了下，发现触发到    abort();   后，它的崩溃日志会显示到下面的方法 sureButtonClick 但是实际上并不是，从崩溃信息来看，它依旧是 abort(); 所以被杀死

@shichuanyang
